In [1]:
Matrices

Matrices are advance versions of atomic vectors with dimensions as a special attribute.

Thus,we can say matrices are special kind of vectors.

Matrices are two dimensional data structures in R. The dimensions are popularly known as rows and columns.

Since they are advance types of atomic vectors, so they can only contain elements of same datatypes.

There are different ways to create a matrix in R.

Let's discuss about them in detail.


SyntaxError: invalid syntax (3388789010.py, line 3)

In [2]:
#using matrix keyword 

mat = matrix(1:4) #not specifying number of rows and columns

In [4]:
mat

[,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4

In [ ]:
#change the default filling method

mat = matrix(1:12,nrow = 4, ncol = 3)

In [ ]:
mat

In [13]:
#change the default filling method

mat = matrix(1:12,nrow=4, ncol = 3,byrow=TRUE)

In [14]:
mat

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [ ]:
dim(mat)

In [ ]:
mat = matrix(1:10,nrow=4, ncol = 3,byrow=TRUE)

## you can also give the names of columns and rows in matrix

In [23]:
mat = matrix(1:12,nrow=4, ncol = 3,byrow=TRUE, dimnames = (list(c("R1","R2","R3","R4"),
                                                                c("C1","C2","C3"))))

In [25]:
mat

C1 C2 C3
R1  1  2  3
R2  4  5  6
R3  7  8  9
R4 10 11 12

### you can get column and row names using function colnames and rownames

In [26]:
rownames(mat)

[1] "R1" "R2" "R3" "R4"

In [27]:
colnames(mat)

[1] "C1" "C2" "C3"

## you can get dimension of matrix using dim( function)

In [17]:
dim(mat)

[1] 4 3

In [18]:
y = matrix(nrow = 2, ncol = 2)



In [19]:
y[1,1] = 1

y[2,1] = 2

y[1,2] = 3

y[2,2] = 4



In [20]:
y

[,1] [,2]
[1,] 1    3   
[2,] 2    4

## Another method

In [ ]:
vec = c(1.2,3.2,4.5,46,54,21)

In [ ]:
vec

In [ ]:
# you can call dimension function with dim() function

dim(vec) = c(3,2)

In [ ]:
vec

In [27]:
# you can add column and row name to this matrix using rownames() and colnames() function

colnames(vec) <- c("A","B")
rownames(vec) <- c("a","b","c")

In [28]:
vec

A   B 
a 1.2 46
b 3.2 54
c 4.5 21

## Using rbind & cbind to create a matrix¶

In [ ]:
mat3 <- cbind(c(1,2,3,4,5,6)) #creating matrix of one column

In [ ]:
mat3

In [ ]:
mat3 <- cbind(c(1,2,3),c(12,13,14))

In [ ]:
mat3

In [ ]:
mat4 <- rbind(c(1,2,3,4,5,6)) #matrix of one row

In [ ]:
mat4

In [12]:
mat4 <- rbind(c(1,2,3),c(4,5,6)) #matrix of two row

In [13]:
mat4

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

### Accesing elements from Matrix¶

In [32]:
mat <- matrix(100:115 , nrow =4,ncol = 4 )

In [33]:
mat

[,1] [,2] [,3] [,4]
[1,] 100  104  108  112 
[2,] 101  105  109  113 
[3,] 102  106  110  114 
[4,] 103  107  111  115

In [34]:
colnames(mat) = c("A","B","C","D")


In [35]:
rownames(mat) = c("1","2","3","4")

In [36]:
mat

A   B   C   D  
1 100 104 108 112
2 101 105 109 113
3 102 106 110 114
4 103 107 111 115

In [37]:
#access first element

mat[1]

[1] 100

In [38]:
#access 15th element

mat[15]

[1] 114

In [91]:
mat[10]

[1] 109

In [7]:
#access all element of row 3

mat[3,]

NameError: name 'mat' is not defined

In [39]:
#access multiple rows

mat[c(2,4),]

A   B   C   D  
2 101 105 109 113
4 103 107 111 115

In [94]:
#access all element of column 

mat[,"A"]

1   2   3   4 
100 101 102 103

In [96]:
#access all element of column 
mat[,1]

1   2   3   4 
100 101 102 103

In [97]:
#access multiple columns

mat[,c("A","B")]

A   B  
1 100 104
2 101 105
3 102 106
4 103 107

In [98]:
mat[,c(1,2)]

A   B  
1 100 104
2 101 105
3 102 106
4 103 107

In [99]:
# access element from a row and column

mat[4,2] #get element from 4throw and 2nd column

[1] 107

In [100]:
mat[4,][3]

C 
111

In [101]:
mat[4,][2] # you can also use this method

B 
107

In [102]:
mat[1,]["B"]

B 
104

In [103]:
mat

A   B   C   D  
1 100 104 108 112
2 101 105 109 113
3 102 106 110 114
4 103 107 111 115

In [104]:
# accessing multiple rows and columns

mat[c(1,4),c("C","D")]

C   D  
1 108 112
4 111 115

### Dropping value from matrix

In [40]:
mat[-1:-2,] #prints all rows without 1st row

A   B   C   D  
3 102 106 110 114
4 103 107 111 115

In [106]:
mat[,-4]  #drops 4th columns

A   B   C  
1 100 104 108
2 101 105 109
3 102 106 110
4 103 107 111

#### But this does not drop row or column from the matrix actually

In [107]:
mat

A   B   C   D  
1 100 104 108 112
2 101 105 109 113
3 102 106 110 114
4 103 107 111 115

#### If you want to drop values from matrix actually

In [108]:
mat_new <- mat[-1,]

In [109]:
mat_new

A   B   C   D  
2 101 105 109 113
3 102 106 110 114
4 103 107 111 115

In [110]:
mat

A   B   C   D  
1 100 104 108 112
2 101 105 109 113
3 102 106 110 114
4 103 107 111 115

### Accessing elements using logical opeartors

In [111]:
mat[1]

[1] 100

In [112]:
mat[(TRUE)] # mat[c(TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,)]

[1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115

In [113]:
mat[1,]

A   B   C   D 
100 104 108 112

In [114]:
mat[(TRUE),]

A   B   C   D  
1 100 104 108 112
2 101 105 109 113
3 102 106 110 114
4 103 107 111 115

In [115]:
mat[c(1,2)]

[1] 100 101

In [116]:
mat[c(TRUE,FALSE)] #get numbers at odd index #recylcing 

[1] 100 102 104 106 108 110 112 114

In [117]:
mat[c(1,2),]

A   B   C   D  
1 100 104 108 112
2 101 105 109 113

In [118]:
mat[c(TRUE,FALSE),] #get numbers at odd index #recylcing 

A   B   C   D  
1 100 104 108 112
3 102 106 110 114

In [119]:
mat[c(FALSE,TRUE)]#get numbers at even index  #recylcing 

[1] 101 103 105 107 109 111 113 115

In [120]:
mat[c(FALSE,TRUE),]

A   B   C   D  
2 101 105 109 113
4 103 107 111 115

In [121]:
mat[c(FALSE,TRUE),c(TRUE,TRUE)]

A   B   C   D  
2 101 105 109 113
4 103 107 111 115

In [122]:
mat[c(TRUE,FALSE),c(TRUE,FALSE)]

A   C  
1 100 108
3 102 110

In [123]:
# Using conditional operators

mat[mat<=109]

[1] 100 101 102 103 104 105 106 107 108 109

In [124]:
mat[mat==105]

[1] 105

#### Modify elements of a Matrix

In [125]:
mat

A   B   C   D  
1 100 104 108 112
2 101 105 109 113
3 102 106 110 114
4 103 107 111 115

In [126]:
mat[1,][3]

C 
108

In [127]:
mat[1,][3] = 801

In [128]:
mat[1,][3]

C 
801

In [129]:
mat

A   B   C   D  
1 100 104 801 112
2 101 105 109 113
3 102 106 110 114
4 103 107 111 115

In [130]:
mat[,"A"] 

1   2   3   4 
100 101 102 103

In [131]:
mat[,"A"] =c(1,11,12,13)

In [132]:
mat

A  B   C   D  
1  1 104 801 112
2 11 105 109 113
3 12 106 110 114
4 13 107 111 115

In [133]:
class(mat[1])

[1] "numeric"

In [134]:
mat[10] ="AB"

In [135]:
mat

A  B   C   D  
1 1  104 801 112
2 11 105 AB  113
3 12 106 110 114
4 13 107 111 115

In [136]:
class(mat[10])

[1] "character"

In [137]:
class(mat[1])

[1] "character"

#### Arithmetic operations on Matrix

In [138]:
mat1 = matrix(1:9, nrow=3,ncol=3)

In [139]:
mat1

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [140]:
mat2 = matrix(10:18,nrow=3,ncol=3)

In [141]:
mat2

[,1] [,2] [,3]
[1,] 10   13   16  
[2,] 11   14   17  
[3,] 12   15   18

In [142]:
#sum of matrices
mat1 + mat2 #element wise sum will happen

[,1] [,2] [,3]
[1,] 11   17   23  
[2,] 13   19   25  
[3,] 15   21   27

In [143]:
#element wise matrix multiplication using * operator

mat1 * mat2 

[,1] [,2] [,3]
[1,] 10   52   112 
[2,] 22   70   136 
[3,] 36   90   162

In [144]:
# let try to add matrx of different sizes

mat3 <- matrix(1:6,nrow=3)

In [145]:
mat3

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [146]:
mat1 + mat3

ERROR: Error in mat1 + mat3: non-conformable arrays


In [147]:
mat1 * mat3

ERROR: Error in mat1 * mat3: non-conformable arrays


In [148]:
#### Matrix Multiplication

In [149]:
mat1 %*% mat2

[,1] [,2] [,3]
[1,] 138  174  210 
[2,] 171  216  261 
[3,] 204  258  312

In [150]:
#let's try to do matrix multiplication with matrices of different size

 mat3 %*% mat1

ERROR: Error in mat3 %*% mat1: non-conformable arguments


#### Transposing matrix

In [151]:
mat3

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [152]:
mat3_transpose = t(mat3)

In [153]:
mat3_transpose

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [154]:
mat3_transpose %*% mat1

[,1] [,2] [,3]
[1,] 14   32    50 
[2,] 32   77   122

#### Applying Functions to Matrix Rows and Columns

#### Using the apply() Function
This is the general form of apply for matrices:

apply(m,dimcode,f,fargs)

where the arguments are as follows:

• m is the matrix.

• dimcode is the dimension, equal to 1 if the function applies to rows or 2
for columns.

• f is the function to be applied.

• fargs is an optional set of arguments to be supplied to f.

In [155]:
m = matrix(1:6, nrow = 3)

In [156]:
m

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [157]:
# apply the R function mean() to each column of a matrix

apply(m,2,mean)  # 2 represents columns   1 represents rows

[1] 2 5

#### Arrays

Arrays are matrices with more than 2 dimensions i.e. arrays are multi dimensional matrices.


In [158]:
arr = array(1:12,dim=c(2,2,3)) #dimension represents rows,columns and number of matrices

#so we basically are creating 3 matrices of dim 2*2

In [159]:
arr

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

, , 3

     [,1] [,2]
[1,]    9   11
[2,]   10   12

In [160]:
print(arr)

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

, , 3

     [,1] [,2]
[1,]    9   11
[2,]   10   12



#### Naming Col and Rows¶

In [43]:
vec1 = c(1,2,3,4)
vec2 = c(7,8,9,10)

colnames = c("A","B")
rownames = c("a","b")

mat_names = c("Mat1","Mat2")

In [44]:
arr_mat = array(c(vec1,vec2),dim = c(2,2,2), dimnames = list(rownames,colnames,mat_names))

In [45]:
print(arr_mat)

, , Mat1

  A B
a 1 3
b 2 4

, , Mat2

  A  B
a 7  9
b 8 10



#### Accessing elements from arrays

In [46]:
arr_mat[1,1,1] #first row first column from first matrix

[1] 1

In [47]:
arr_mat[1,1,2] #first row first column from second matrix

[1] 7

In [48]:
arr_mat[2,,2] #whole second row from second matrix

A  B 
 8 10

In [49]:
arr_mat[,,1] #all elements of first matrix

A B
a 1 3
b 2 4

In [50]:
arr_mat[1,1,]

Mat1 Mat2 
   1    7